#!/usr/bin/env python3
"""Bundle the runtime into one self-contained tournament file.

Many school tournaments accept exactly one ``.py`` file, so the package is
flattened here rather than maintained twice.  Development code - the
simulator, the bot population, the optimiser, the benchmarks - is deliberately
left out: it is dead weight in a submission and every line of it is another
line that could fail at the wrong moment.

The bundler concatenates runtime modules in dependency order, strips the
intra-package imports (everything ends up in one namespace), hoists and
de-duplicates the standard-library imports, and appends the tuned weights plus
a generous set of entry points.
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

#: Dependency order.  Each module may only reference names defined above it.
RUNTIME_MODULES = [
    "superpac/game/rules.py",
    "superpac/game/map_model.py",
    "superpac/game/state.py",
    "superpac/opponents/context_model.py",
    "superpac/opponents/sequence_model.py",
    "superpac/opponents/periodicity.py",
    "superpac/opponents/pattern_detector.py",
    "superpac/opponents/hidden_state.py",
    "superpac/opponents/predictor.py",
    "superpac/opponents/model.py",
    "superpac/ai/territory.py",
    "superpac/ai/threat.py",
    "superpac/ai/evaluator.py",
    "superpac/ai/strategy.py",
    "superpac/ai/planner.py",
    "superpac/ai/superpac.py",
    "superpac/game/adapter.py",
]

RELATIVE_IMPORT = re.compile(r"^\s*from\s+\.+[\w.]*\s+import\s+.*$", re.M)
PACKAGE_IMPORT = re.compile(r"^\s*from\s+superpac[\w.]*\s+import\s+.*$", re.M)
ALL_ASSIGN = re.compile(r"^__all__\s*=\s*\[.*?\]\s*$", re.M | re.S)
FUTURE = re.compile(r"^\s*from\s+__future__\s+import\s+.*$", re.M)


def strip_module(path: str):
    """Return ``(body, stdlib_import_lines)`` for one module.

    Uses the AST rather than line regexes: several modules wrap their imports
    across multiple lines, and a regex that matches only the first line leaves
    a dangling continuation behind.  ``lineno``/``end_lineno`` give the exact
    span to cut regardless of formatting.
    """
    with open(os.path.join(ROOT, path)) as fh:
        source = fh.read()
    lines = source.splitlines()
    tree = ast.parse(source)

    drop = set()
    imports = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                drop.add(lineno)
            module = getattr(node, "module", None) or ""
            level = getattr(node, "level", 0)
            if level > 0 or module.startswith("superpac"):
                continue  # intra-package: everything shares one namespace now
            if module == "__future__":
                continue  # hoisted once into the header
            if isinstance(node, ast.Import):
                for alias in node.names:
                    text = f"import {alias.name}"
                    if alias.asname:
                        text += f" as {alias.asname}"
                    imports.append(text)
            else:
                names = ", ".join(
                    a.name + (f" as {a.asname}" if a.asname else "")
                    for a in node.names)
                imports.append(f"from {module} import {names}")
        elif isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
            if targets == ["__all__"]:
                for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                    drop.add(lineno)

    # A relative import nested inside a function survives the flattening and
    # then explodes at run time with "no known parent package".  Catch it here
    # instead of in the tournament.
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.lineno not in drop:
            module = node.module or ""
            if node.level > 0 or module.startswith("superpac"):
                raise SystemExit(
                    f"{path}:{node.lineno}: intra-package import nested inside a "
                    f"function; hoist it to module level so the bundle can flatten it")

    body = "\n".join(line for i, line in enumerate(lines, 1) if i not in drop)
    return body.strip("\n"), imports


HEADER = '''"""SUPERPAC - adaptive multi-agent competitive game AI.

Single-file tournament build.  Generated by scripts/build_submission.py from
the superpac/ package; edit the package, not this file.

What it does, per turn:

    observe every rival's move
      -> update one independent behavioural model per rival
      -> mix competing hypotheses about each rival's policy by how well they
         have actually predicted it
      -> forecast probable rival positions several turns ahead
      -> build territory, threat and food-potential maps
      -> pick a strategy for the current situation
      -> search our own move sequences under a time budget
      -> choose the move that stays good even when the prediction is wrong

Guarantees: always returns a legal action, never raises out of ``act``, and
respects the per-move time limit via an anytime search with a safety margin.

Built: {built}
Weights: {weights_source}
"""

from __future__ import annotations

{imports}

# ``dataclasses`` resolves string annotations via ``sys.modules[cls.__module__]``
# and crashes outright if that entry is missing.  A normal ``import`` always
# creates it, but a host that loads this file through ``importlib`` without
# registering it first would take the whole submission down before the first
# turn.  Registering a stand-in costs nothing and removes the failure mode.
if sys.modules.get(__name__) is None:  # pragma: no cover - loader guard
    sys.modules[__name__] = types.ModuleType(__name__)

'''

FOOTER = '''

# ==========================================================================
# Tuned parameters
# ==========================================================================
# Produced by superpac/training/optimize_weights.py: evolutionary search on a
# training opponent population, champion selected on a disjoint validation
# population so the numbers describe strong play rather than memorised
# opponents.
TUNED_WEIGHTS = {weights_dict}

WEIGHTS = Weights(**TUNED_WEIGHTS)


# ==========================================================================
# Entry points
# ==========================================================================
# The tournament API is not documented in this repository, so rather than
# guessing one signature this exposes several and lets the host pick.  The
# adapter underneath sniffs the state object it is handed - see
# ``StateExtractor`` - and caches what it learns after the first turn.
#
# If the real API turns out to differ, the fix is here and in
# ``StateExtractor``; nothing above this line needs to change.

class SuperPacPlayer:
    """The submission.  Instantiate once per match; it keeps its own memory."""

    name = "SUPERPAC"

    def __init__(self, player_id: int = 0, *args, **kwargs) -> None:
        self.player_id = player_id
        self.extractor = StateExtractor()
        self.brain = SuperPac(weights=WEIGHTS)
        self._started = False
        self._last_action = STAY

    # -- the many names a host might call ------------------------------
    def get_move(self, state=None, extra=None):
        return self._decide(state, extra)

    def choose_action(self, state=None, extra=None):
        return self._decide(state, extra)

    def move(self, state=None, extra=None):
        return self._decide(state, extra)

    def next_move(self, state=None, extra=None):
        return self._decide(state, extra)

    def act(self, state=None, extra=None):
        # A native GameState (our own simulator) skips the adapter entirely.
        if isinstance(state, GameState):
            return self.brain.act(state)
        return self._decide(state, extra)

    def play(self, state=None, extra=None):
        return self._decide(state, extra)

    def __call__(self, state=None, extra=None):
        return self._decide(state, extra)

    def reset(self, state=None, player_id: int = 0):
        self.player_id = player_id
        self._started = False
        if isinstance(state, GameState):
            self.brain.reset(state, player_id)

    # ------------------------------------------------------------------
    def _decide(self, raw, extra=None):
        """Translate, think, translate back - and never let go of the turn."""
        try:
            state = self.extractor.extract(raw, extra)
            if not self._started:
                self.brain.reset(state, state.me)
                self._started = True
            action = self.brain.act(state)
            self._last_action = action
            return self.extractor.encode_action(action)
        except Exception:
            # The host is owed a move even when everything above has failed.
            return self.extractor.encode_action(self._panic(raw, extra))

    def _panic(self, raw, extra):
        try:
            state = self.extractor.extract(raw, extra)
            return self.brain.fallback(state)
        except Exception:
            return self._last_action if self._last_action != STAY else EAST


# Aliases, because the host may look for any of these names.
Player = SuperPacPlayer
Bot = SuperPacPlayer
Agent = SuperPacPlayer
AI = SuperPacPlayer
MyPlayer = SuperPacPlayer
Superpac = SuperPacPlayer

_SINGLETON = None


def _singleton() -> SuperPacPlayer:
    global _SINGLETON
    if _SINGLETON is None:
        _SINGLETON = SuperPacPlayer()
    return _SINGLETON


def get_move(state=None, extra=None):
    """Module-level entry point for hosts that call a function, not a class."""
    return _singleton().get_move(state, extra)


def choose_action(state=None, extra=None):
    return _singleton().get_move(state, extra)


def move(state=None, extra=None):
    return _singleton().get_move(state, extra)


def next_move(state=None, extra=None):
    return _singleton().get_move(state, extra)


def reset(state=None, player_id: int = 0):
    global _SINGLETON
    _SINGLETON = None


def inspect_api(state, extra=None) -> str:
    """Run this ONCE against the real engine to discover its actual API.

    Prints what the sniffer found in the host's state object.  Whatever it
    reports is what to pin in ``StateExtractor`` for a build that does no
    guessing at all.
    """
    return describe_host_state(state, extra)


if __name__ == "__main__":  # pragma: no cover - self-check
    _selftest()
'''

SELFTEST = '''

def _selftest() -> None:
    """Prove the bundle works standalone: build a map, play, check timing."""
    import random as _random
    import time as _time

    lines = [
        "#####################",
        "#...................#",
        "#.###.#####.#####.#.#",
        "#.....#.........#...#",
        "#.###.#.#######.#.#.#",
        "#...#...#.....#...#.#",
        "###.#####.###.#####.#",
        "#.........#.#.......#",
        "#.#####.#.#.#.#####.#",
        "#.......#.....#.....#",
        "#####################",
    ]
    width = len(lines[0])
    height = len(lines)
    passable = bytearray(width * height)
    for y, row in enumerate(lines):
        for x, ch in enumerate(row):
            passable[y * width + x] = 0 if ch == "#" else 1
    graph = MapGraph(width, height, passable)
    cells = list(graph.cells)
    rng = _random.Random(7)
    spawns = [cells[0], cells[len(cells) // 3], cells[2 * len(cells) // 3], cells[-1]]
    food = set(cells) - set(spawns)
    state = GameState(graph, food, spawns, me=0)

    player = SuperPacPlayer()
    worst = 0.0
    total = 0.0
    turns = 0
    for _ in range(160):
        if state.is_terminal():
            break
        actions = []
        for pid in range(state.n_players):
            state.me = pid
            state._legal_cache = None
            if not state.alive[pid]:
                actions.append(STAY)
                continue
            if pid == 0:
                t0 = _time.perf_counter()
                action = player.act(state)
                elapsed = (_time.perf_counter() - t0) * 1000.0
                worst = max(worst, elapsed)
                total += elapsed
                turns += 1
            else:
                legal = state.legal_actions(pid)
                _, _, action = graph.nearest_target(state.positions[pid], state.food)
                if action not in legal:
                    action = rng.choice(legal)
            assert action in state.legal_actions(pid), "illegal action returned"
            actions.append(action)
        state.me = 0

        # Minimal inline resolution: move, then eat.
        for pid in range(state.n_players):
            if state.alive[pid]:
                state.positions[pid] = graph.step(state.positions[pid], actions[pid])
        for pid in range(state.n_players):
            if state.alive[pid] and state.positions[pid] in state.food:
                state.food.discard(state.positions[pid])
                state.scores[pid] += 1.0
        state.turn += 1

    print("SUPERPAC self-test")
    print(f"  map            : {width}x{height}, {len(graph.cells)} walkable cells")
    print(f"  turns played   : {turns}")
    print(f"  scores         : {[int(s) for s in state.scores]}")
    print(f"  mean move time : {total / max(1, turns):.2f} ms")
    print(f"  worst move time: {worst:.2f} ms")
    print(f"  faults         : {player.brain.faults}")
    assert player.brain.faults == 0, "fallback path was used"
    print("  OK - legal every turn, no faults")
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", default="results/weights_champion.json")
    ap.add_argument("--out", default="submission/superpac.py")
    args = ap.parse_args()

    weights_path = os.path.join(ROOT, args.weights)
    if os.path.exists(weights_path):
        with open(weights_path) as fh:
            payload = json.load(fh)
        weights_dict = payload["weights"]
        source = f"tuned ({args.weights})"
    else:
        from superpac.ai.evaluator import Weights
        weights_dict = Weights().to_dict()
        source = "hand-set defaults (no tuned file found)"

    bodies = []
    all_imports = []
    for path in RUNTIME_MODULES:
        body, imports = strip_module(path)
        all_imports.extend(imports)
        bodies.append(f"# {'=' * 74}\n# {path}\n# {'=' * 74}\n\n{body}")

    all_imports.extend(["import sys", "import types"])
    seen = set()
    ordered_imports = []
    for line in all_imports:
        if line not in seen:
            seen.add(line)
            ordered_imports.append(line)
    ordered_imports.sort(key=lambda l: (not l.startswith("import "), l))

    formatted = json.dumps(weights_dict, indent=4).replace("true", "True").replace("false", "False")
    text = (
        HEADER.format(built=time.strftime("%Y-%m-%d"),
                      weights_source=source,
                      imports="\n".join(ordered_imports))
        + "\n\n".join(bodies)
        + SELFTEST
        + FOOTER.format(weights_dict=formatted)
    )

    out_path = os.path.join(ROOT, args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write(text)

    ast.parse(text)  # fail loudly here rather than in the tournament
    lines = text.count("\n") + 1
    print(f"wrote {args.out}: {lines} lines, {len(text) / 1024:.0f} KB")
    print(f"weights: {source}")


if __name__ == "__main__":
    main()
