#!/usr/bin/env python3
"""Build the deliverable ``Pacman.py``: the teacher's engine + our ThoresT.

The teacher's ``Field.__init__`` instantiates ``ThoresT`` from its own module
globals, so our player has to live in that file.  Rather than maintaining a
copy of the AI by hand, this flattens the runtime modules into the engine
file and replaces the empty stub at the end.

The engine's own code is copied through **unmodified** - only the ``ThoresT``
stub is replaced.  That matters: the tournament runs the teacher's rules, and
a build step that quietly edited them would invalidate every measurement.
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

#: Dependency order; each may only use names defined above it.
RUNTIME = [
    "superpac/pacman/rules.py",
    "superpac/pacman/perception.py",
    "superpac/pacman/model.py",
    "superpac/pacman/agent.py",
]


def strip_module(path: str):
    """Return ``(body, stdlib_imports)`` with all package imports removed.

    Imports of the engine's own names (``from Pacman import Cabbage``) are
    dropped too: inside the bundle those classes are already module globals,
    and re-importing the module from inside itself is a circular import that
    fails when the file is run as ``__main__``.
    """
    with open(os.path.join(ROOT, path)) as fh:
        source = fh.read()
    lines = source.splitlines()
    tree = ast.parse(source)

    drop = set()
    imports = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        module = getattr(node, "module", None) or ""
        level = getattr(node, "level", 0)
        internal = (level > 0 or module.startswith("superpac")
                    or module == "Pacman" or module == "__future__")
        if internal:
            for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                drop.add(lineno)
            continue
        if node.col_offset != 0:
            continue  # a nested stdlib import: leave it where it is
        for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
            drop.add(lineno)
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.append(f"import {alias.name}"
                               + (f" as {alias.asname}" if alias.asname else ""))
        else:
            names = ", ".join(a.name + (f" as {a.asname}" if a.asname else "")
                              for a in node.names)
            imports.append(f"from {module} import {names}")

    for node in tree.body:
        if isinstance(node, ast.Assign):
            if [t.id for t in node.targets if isinstance(t, ast.Name)] == ["__all__"]:
                for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                    drop.add(lineno)

    kept = [line for i, line in enumerate(lines, 1) if i not in drop]
    body = "\n".join(kept).strip("\n")
    # A dropped import may leave an empty function body behind.
    if re.search(r"\n\s*\n\s*(return|pass)?\s*$", body) is None:
        pass
    return body, imports


HEADER = '''
# ==========================================================================
# ThoresT - adaptive Pacman player
# ==========================================================================
# Generated by scripts/build_pacman.py from the superpac/pacman package.
# Edit the package, not this section.  Everything above this line is the
# teacher's engine, copied through unchanged.
#
# How it plays, in one paragraph:
#
#   The board is a torus with no walls, every cell starts as cabbage, and a
#   turn is spent EITHER turning OR moving - never both.  So a long straight
#   run through cabbage is the cheapest strength available, and the bot plans
#   in runs rather than in paths.  Six players strip a 15x15 board by about
#   turn 55; after that the only strength left on the table is other players,
#   so it switches to hunting.  Combat is decided by relative facing: a
#   target running the same way you are defends at a tenth of its strength,
#   so it attacks from behind and, when attacked, turns to face the attacker
#   (which cuts their odds from 91% to 50%).  It keeps a behaviour model of
#   every rival - their actions are exactly recoverable from the board - and
#   uses it to predict who is about to move where.
#
# Built: {built}
# Weights: {weights_source}
# ==========================================================================

{imports}

'''

FOOTER = '''

# ==========================================================================
# Tuned parameters
# ==========================================================================
# Found by scripts/tune_thorest.py: evolutionary search on the real engine
# against strong opponents (harvesters, sweepers, hunters), with the champion
# selected on a separate opponent mix so the numbers describe good play
# rather than memorised opponents.
TUNED_WEIGHTS = {weights_dict}

THORES_WEIGHTS = Weights(**TUNED_WEIGHTS)


class ThoresT(Pacman):
    """Our tournament player."""

    def __init__(self, p, name, field):
        super().__init__(p, name, field)
        self.logo = "T"
        self.direction = Direction.west
        self.brain = Brain(weights=THORES_WEIGHTS, total_turns=TOTAL_TURNS)

    def TurnOrMoveOrStill(self):
        # The engine ignores the return value, so anything escaping this
        # method forfeits the turn - or, in a tournament, the match.
        try:
            action = self.brain.decide(self)
        except Exception:
            self.brain.faults += 1
            action = MOVE
        try:
            if action < 4:
                self.direction = _DIRECTION_OBJECTS[action]
            elif action == MOVE:
                self._Move()
            # STILL: deliberately nothing
        except Exception:
            self.brain.faults += 1


_DIRECTION_OBJECTS = (Direction.north, Direction.south,
                      Direction.west, Direction.east)

#: Match length the engine's own test notebook uses.  Only feeds the
#: "how much harvest is left" estimate, which decides when hunting becomes
#: worth more than farming; a wrong value costs sharpness, not correctness.
TOTAL_TURNS = 100


if __name__ == "__main__":  # pragma: no cover - self-check
    import random as _random
    import time as _time

    _random.seed(1)
    _board = Field(15)
    _me = _board.pacmans[-1]
    _worst = 0.0
    for _turn in range(100):
        for _p in _board.pacmans:
            if not _p.alive:
                continue
            if _p is _me:
                _t0 = _time.perf_counter()
                _p.TurnOrMoveOrStill()
                _worst = max(_worst, (_time.perf_counter() - _t0) * 1000.0)
            else:
                _p.TurnOrMoveOrStill()
    print("ThoresT self-test")
    print("  final strengths:")
    for _p in _board.pacmans:
        print(f"    {_p.name:<10s} {_p.strength:6.0f}"
              + ("" if _p.alive else "   (dead)"))
    _rivals = [_p.strength for _p in _board.pacmans if _p is not _me]
    print(f"  ThoresT {_me.strength:.0f} vs best rival {max(_rivals):.0f}"
          f"  -> {'WIN' if _me.strength > max(_rivals) else 'loss'}")
    print(f"  mean {_me.brain.total_ms / max(1, _me.brain.turn):.2f} ms/turn, "
          f"worst {_worst:.2f} ms, faults {_me.brain.faults}")
    assert _me.brain.faults == 0, "the fallback path was used"
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", default="results/thorest_weights.json")
    ap.add_argument("--engine", default="teacher/Pacman_original.py")
    ap.add_argument("--out", default="Pacman.py")
    args = ap.parse_args()

    weights_path = os.path.join(ROOT, args.weights)
    if os.path.exists(weights_path):
        with open(weights_path) as fh:
            weights_dict = json.load(fh)["weights"]
        source = f"tuned ({args.weights})"
    else:
        from superpac.pacman.agent import Weights
        weights_dict = {n: getattr(Weights(), n) for n in Weights.names()}
        source = "hand-set defaults (no tuned file found)"

    with open(os.path.join(ROOT, args.engine)) as fh:
        engine = fh.read()

    # Cut the stub, keep everything else byte-for-byte.
    marker = engine.index("class ThoresT(Pacman):")
    engine_body = engine[:marker].rstrip("\n")

    bodies, all_imports = [], []
    for path in RUNTIME:
        body, imports = strip_module(path)
        all_imports.extend(imports)
        bodies.append(f"# {'-' * 70}\n# {path}\n# {'-' * 70}\n\n{body}")

    seen, ordered = set(), []
    for line in all_imports:
        if line not in seen and not line.startswith("import random"):
            seen.add(line)
            ordered.append(line)
    ordered.sort(key=lambda l: (not l.startswith("import "), l))

    formatted = json.dumps(weights_dict, indent=4)
    # Plain substitution rather than str.format: the footer contains f-strings
    # of its own, and format() would try to interpolate their braces.
    header = (HEADER.replace("{built}", time.strftime("%Y-%m-%d"))
                    .replace("{weights_source}", source)
                    .replace("{imports}", "\n".join(ordered)))
    footer = FOOTER.replace("{weights_dict}", formatted)
    text = engine_body + "\n\n" + header + "\n\n".join(bodies) + footer

    ast.parse(text)
    out_path = os.path.join(ROOT, args.out)
    with open(out_path, "w") as fh:
        fh.write(text)
    print(f"wrote {args.out}: {text.count(chr(10)) + 1} lines, {len(text) / 1024:.0f} KB")
    print(f"weights: {source}")


if __name__ == "__main__":
    main()
